'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var template = {};

template.es = function (tpls, scripts, libs) {
  return (libs ? libs + '\n' : '') + '\nclass CoreClass {\n  constructor() {\n    this.tpls = {};\n    this.scripts = {};\n    this.datas = {};\n    this._initTpls()._initScripts();\n    return this;\n  }\n\n  _generate() {\n    return Math.random().toString().replace(\'.\', \'\');\n  }\n\n  _initTpls() {\n    let $NODETPL = this;\n    this.tpls = {\n      ' + tpls.join(',') + '\n    };\n    return $NODETPL;\n  }\n\n  _initScripts() {\n    let $NODETPL = this;\n    this.scripts = {\n      ' + scripts.join(',') + '\n    };\n    return $NODETPL;\n  }\n\n  duid() {\n    return \'nodetpl_d_\' + this._generate();\n  }\n\n  guid() {\n    return \'nodetpl_g_\' + this._generate();\n  }\n\n  escapeHtml(html) {\n    return html.toString().replace(/&/g, \'&amp;\').replace(/</g, \'&lt;\').replace(/>/g, \'&gt;\').replace(/"/g, \'&quot;\').replace(/\'/g, \'&#39;\');\n  }\n\n  render(data, guid) {\n    return this.tpls.main(data, guid || this.guid());\n  }\n}\n\nexport default {\n  render: data => new CoreClass().render(data)\n};';
};

template.commonjs = template.node = function (tpls, scripts, libs) {
  return (libs ? libs + '\n' : '') + '\nclass CoreClass {\n  constructor() {\n    this.tpls = {};\n    this.scripts = {};\n    this.datas = {};\n    this._initTpls()._initScripts();\n    return this;\n  }\n\n  _generate() {\n    return Math.random().toString().replace(\'.\', \'\');\n  }\n\n  _initTpls() {\n    let $NODETPL = this;\n    this.tpls = {\n      ' + tpls.join(',') + '\n    };\n    return $NODETPL;\n  }\n\n  _initScripts() {\n    let $NODETPL = this;\n    this.scripts = {\n      ' + scripts.join(',') + '\n    };\n    return $NODETPL;\n  }\n\n  duid() {\n    return \'nodetpl_d_\' + this._generate();\n  }\n\n  guid() {\n    return \'nodetpl_g_\' + this._generate();\n  }\n\n  escapeHtml(html) {\n    return html.toString().replace(/&/g, \'&amp;\').replace(/</g, \'&lt;\').replace(/>/g, \'&gt;\').replace(/"/g, \'&quot;\').replace(/\'/g, \'&#39;\');\n  }\n\n  render(data, guid) {\n    return this.tpls.main(data, guid || this.guid());\n  }\n}\n\nmodule.exports = {\n  render: data => new CoreClass().render(data)\n};';
};

template.amd = template.cmd = function (tpls, scripts, libs) {
  return 'define(function(require, exports, module){\n  ' + (libs ? libs + '\n' : '') + '\n  class CoreClass {\n    constructor() {\n      this.tpls = {};\n      this.scripts = {};\n      this.datas = {};\n      this._initTpls()._initScripts();\n      return this;\n    }\n\n    _generate() {\n      return Math.random().toString().replace(\'.\', \'\');\n    }\n\n    _initTpls() {\n      let $NODETPL = this;\n      this.tpls = {\n        ' + tpls.join(',') + '\n      };\n      return $NODETPL;\n    }\n\n    _initScripts() {\n      let $NODETPL = this;\n      this.scripts = {\n        ' + scripts.join(',') + '\n      };\n      return $NODETPL;\n    }\n\n    duid() {\n      return \'nodetpl_d_\' + this._generate();\n    }\n\n    guid() {\n      return \'nodetpl_g_\' + this._generate();\n    }\n\n    escapeHtml(html) {\n      return html.toString().replace(/&/g, \'&amp;\').replace(/</g, \'&lt;\').replace(/>/g, \'&gt;\').replace(/"/g, \'&quot;\').replace(/\'/g, \'&#39;\');\n    }\n\n    render(data, guid) {\n      return this.tpls.main(data, guid || this.guid());\n    }\n  }\n\n  return {\n    render: data => new CoreClass().render(data)\n  };\n});';
};

template.var = function (tpls, scripts, libs) {
  return '((nodetpl) => {\n  ' + (libs ? libs + '\n' : '') + '\n  class CoreClass {\n    constructor() {\n      this.tpls = {};\n      this.scripts = {};\n      this.datas = {};\n      this._initTpls()._initScripts();\n      return this;\n    }\n\n    _generate() {\n      return Math.random().toString().replace(\'.\', \'\');\n    }\n\n    _initTpls() {\n      let $NODETPL = this;\n      this.tpls = {\n        ' + tpls.join(',') + '\n      };\n      return $NODETPL;\n    }\n\n    _initScripts() {\n      let $NODETPL = this;\n      this.scripts = {\n        ' + scripts.join(',') + '\n      };\n      return $NODETPL;\n    }\n\n    duid() {\n      return \'nodetpl_d_\' + this._generate();\n    }\n\n    guid() {\n      return \'nodetpl_g_\' + this._generate();\n    }\n\n    escapeHtml(html) {\n      return html.toString().replace(/&/g, \'&amp;\').replace(/</g, \'&lt;\').replace(/>/g, \'&gt;\').replace(/"/g, \'&quot;\').replace(/\'/g, \'&#39;\');\n    }\n\n    render(data, guid) {\n      return this.tpls.main(data, guid || this.guid());\n    }\n  }\n  let url = nodetpl._getCurrentScript();\n  nodetpl.template[url] = new CoreClass();\n})(window.nodetpl);';
};

exports.default = template;